# Generated by Django 5.0.7 on 2026-07-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('default_params', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_filters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('work_schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='RUR', max_length=8)),
                ('salary_basis', models.CharField(choices=[('gross', 'До вычета налогов'), ('net', 'На руки'), ('unknown', 'Не указано')], default='unknown', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='vacancies', to='vacancies.skill')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.parsingsource')),
            ],
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='vacancies.vacancy')),
            ],
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['city'], name='vacancies_v_city_1fd706_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['published_at'], name='vacancies_v_publish_32bff5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'vacancy')},
        ),
    ]
